version: '3.8'

services:
  api:
    container_name: api_container
    restart: always
    build:
      context: Api/.
      dockerfile: Dockerfile
    ports:
      - 5220:8000  # Map port 5220 on host to port 8000 in the container
    environment:
      - ASPNETCORE_URLS=http://+:8000  # Ensure the API listens on port 8000 internally

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web-client_container
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    ports:
      - '4200:4200'
    volumes:
      - ./web-client:/app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true # Enable polling
