version: '3.8'

services:
  api:
    container_name: api_container
    restart: always
    build:
      context: Api/.
      dockerfile: Dockerfile
    ports:
      - 8000:8000 

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: web-client_container
    command: ng serve --host 0.0.0.0 --port 4200 --open
    ports:
      - '4200:4200'
    volumes:
      - ./web-client:/app
    environment:
      NODE_ENV: development